Add php 8.1 Runtime
apache/openwhisk-runtime-php pull request #122
Opened 2022-08-22 11:25 UTC by skywalkeretw

2022-08-22 12:03 UTC, skywalkeretw commented
@dgrove-oss Please review :)

2022-08-23 07:55 UTC, akrabat requested changes
Looks great. Thank you for doing this. Just a few minor tweaks.

2022-08-23 07:55 UTC, akrabat commented on README.md
> +docker tag whisk/php8.0Action $user_prefix/action-php-v8.1
`s/php8.0Action/php8.1Action/` ?

2022-08-23 07:55 UTC, akrabat commented on core/php8.1Action/Dockerfile
> +    # && apt-get purge -y --auto-remove libclang-common-7-dev clang-7 llvm-7 llvm-7-dev \
Can we delete this commented out line?

2022-08-23 07:55 UTC, akrabat commented on core/php8.1Action/runner.php
> +    // cast result to an object for json_encode to ensure that an empty array becomes "{}" & send to fd/3
This comment is wrong as it doesn't do the cast here. Should be:

```
// send result to fd/3
```

2022-08-23 07:55 UTC, akrabat commented on core/php8.1Action/runner.php
> +            $result = json_encode((object)$result);
Add comment before this line:

```
// cast result to an object for json_encode to ensure that an empty array becomes "{}
```

2022-08-24 05:10 UTC, skywalkeretw commented
@akrabat I added your suggested fixes Thanks for the input

2022-08-24 06:50 UTC, akrabat approved these changes
LGTM 👍

2022-08-24 06:51 UTC, ningyougang approved these changes

2022-08-24 10:18 UTC, skywalkeretw commented
Would someone be so kind and merge the pull request thx :)

2022-08-24 11:32 UTC, merged